# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: "aks-federated-identity"

steps:
- script: |
    az account show
  displayName: 'Run Azure CLI'
